apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver
  name:  app
spec:
  containers:
    - name: app
      image: 519511800294.dkr.ecr.us-east-1.amazonaws.com/docker:v3.1
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: DBHOST
          value: "mysql.sunil.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "dbpwd"
        - name: DBPORT
          value: "3306"