apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver
  name:  app_sunil
spec:
  containers:
    - name: app_sunil
      image: 519511800294.dkr.ecr.us-east-1.amazonaws.com/docker:v1.0
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: DBHOST
          value: "mysql.sunil.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "sunil123"
        - name: DBPORT
          value: "3306"