apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app_sunil
        ports:
          - containerPort: 8080
            protocol: TCP
        image: 519511800294.dkr.ecr.us-east-1.amazonaws.com/docker:v1.0
        env:
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "sunil123"
        - name: DBHOST
          value: "mysql.sunil.svc.cluster.local"
        - name: DBUSER
          value: "root"
